#!/usr/bin/env python
import SimpleHTTPServer
import SocketServer
import sys

PORT = int(sys.argv[1])
Handler = SimpleHTTPServer.SimpleHTTPRequestHandler
httpd = SocketServer.TCPServer(("", PORT), Handler)
httpd.serve_forever()
