#!/usr/bin/env python
import BaseHTTPServer
import SocketServer
import sys
import os

script_dir = os.path.dirname(__file__)
resource_name = 'interface.html'
resource_path = os.path.join(script_dir, resource_name)
PORT = int(sys.argv[1])
HOST_NAME = 'localhost'
INDEX = open(resource_path)
print("Web interface: starting on {}:{} serving: {}.".format(HOST_NAME,PORT,resource_path))

class InterfaceHandler(BaseHTTPServer.BaseHTTPRequestHandler):
    def do_HEAD(s):
        s.send_response(200)
        s.send_header("Content-type", "text/html")
        s.end_headers()
    def do_GET(s):
        """Respond to a GET with interface file"""
        s.send_response(200)
        s.send_header("Content-type", "text/html")
        s.end_headers()
        INDEX.seek(0)
        for line in INDEX:
            s.wfile.write(line)

server_class = BaseHTTPServer.HTTPServer
httpd = server_class((HOST_NAME, PORT), InterfaceHandler)
try:
    httpd.serve_forever()
except KeyboardInterrupt:
    pass
print("Server closing.")
httpd.server_close()
