#!/usr/bin/env python

import SimpleHTTPServer
import SocketServer

PORT = 4444

Handler = SimpleHTTPServer.SimpleHTTPRequestHandler

httpd = SocketServer.TCPServer(("", PORT), Handler)

httpd.serve_forever()
